services:
  micro-collector:
    container_name: collector
    build: micro-collector
    ports:
      - "8080:8080"
    networks:
      - recipient
  micro-recipient:
    container_name: recipient
    build: micro-recipient
    ports:
      - "8081:8081"
    networks:
      - recipient
  micro-sender:
    container_name: sender
    build: micro-sender
    ports:
      - "8082:8082"
    networks:
      - sender
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - recipient
      - sender
networks:
  sender: {}
  recipient: {}
