services:
  micro-collector:
    container_name: collector
    build: micro-collector
    ports:
      - "8080:8080"
    networks:
      - recipient
  micro-recipient:
    container_name: recipient
    build: micro-recipient
    ports:
      - "8081:8081"
    networks:
      - recipient
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=amq_notification_queue
      - RABBITMQ_EXCHANGE_NAME=amq_notification_exchange
      - RABBITMQ_ROUTING_KEY=amq_notification_routing_key
      - RABBITMQ_CONSUMER_FIX_DELAY=5000
  micro-sender:
    container_name: sender
    build: micro-sender
    ports:
      - "8082:8082"
    networks:
      - sender
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=amq_notification_queue
      - RABBITMQ_EXCHANGE_NAME=amq_notification_exchange
      - RABBITMQ_ROUTING_KEY=amq_notification_routing_key
      - RABBITMQ_PRODUCER_FIX_DELAY=500
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - recipient
      - sender
  eureka:
    container_name: eureka
    build: eureka-service
    ports:
      - "8761:8761"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
networks:
  sender: { }
  recipient: { }
